import { Ground, GroundSlot, Booking, Team, LeaderboardEntry, MatchChallenge, PlatformStats, DisputeTicket, CricketMatch, TeamMembership, TeamJoinRequest } from '@/types';

export const MOCK_GROUNDS: Ground[] = [
  {
    id: 'ground-1',
    ownerId: 'owner-1',
    name: 'F-6 Box Arena & Indoor Nets',
    location: 'Super Market, F-6 Markaz',
    address: 'Plot 12, School Road, F-6/1, Islamabad',
    city: 'Islamabad',
    pitchType: 'turf_box',
    hourlyRate: 3500,
    rating: 4.8,
    reviewCount: 124,
    distanceKm: 2.1,
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=80',
    description: 'Premier indoor box cricket with imported AstroTurf, automated bowling machines, LED floodlights, and viewing gallery.',
    amenities: ['Bowling Machine', 'Floodlights', 'Changing Rooms', 'Air Conditioned Dugout', 'Free Parking', 'Cricket Gear Available'],
    slotsCountAvailableToday: 6,
    operatingHours: '04:00 PM - 02:00 AM',
    status: 'approved',
  },
  {
    id: 'ground-2',
    ownerId: 'owner-2',
    name: 'Rawal Turf Cricket Hub',
    location: 'Murree Road, Near Chandni Chowk',
    address: 'Near Commercial Market, Murree Road, Rawalpindi',
    city: 'Rawalpindi',
    pitchType: 'indoor_net',
    hourlyRate: 2800,
    rating: 4.6,
    reviewCount: 98,
    distanceKm: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=800&q=80',
    description: '3 dedicated indoor practice nets with high ceiling, side netting, speed gun radar, and professional coach availability.',
    amenities: ['Speed Gun', 'High Ceiling Nets', 'Dressing Room', 'Refreshments Canteen', 'Video Analysis'],
    slotsCountAvailableToday: 8,
    operatingHours: '02:00 PM - 01:00 AM',
    status: 'approved',
  },
  {
    id: 'ground-3',
    ownerId: 'owner-1',
    name: 'Margalla Sports Complex Nets',
    location: 'Sector G-8/4',
    address: 'Street 33, Sector G-8/4, Islamabad',
    city: 'Islamabad',
    pitchType: 'matting',
    hourlyRate: 2500,
    rating: 4.5,
    reviewCount: 65,
    distanceKm: 3.2,
    imageUrl: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?auto=format&fit=crop&w=800&q=80',
    description: 'All-weather indoor matting wicket arena suitable for serious practice and friendly 6-a-side weekend fixtures.',
    amenities: ['Drinking Water', 'Shower Facilities', 'Seating Stands', 'Tape Ball Provided'],
    slotsCountAvailableToday: 4,
    operatingHours: '09:00 AM - 12:00 AM',
    status: 'approved',
  },
  {
    id: 'ground-4',
    ownerId: 'owner-3',
    name: 'Saddar Indoor Smash Arena',
    location: 'Saddar, Cantt',
    address: 'Bank Road, Saddar, Rawalpindi Cantt',
    city: 'Rawalpindi',
    pitchType: 'turf_box',
    hourlyRate: 3200,
    rating: 4.9,
    reviewCount: 154,
    distanceKm: 6.8,
    imageUrl: 'https://images.unsplash.com/photo-1512719355433-e02374b9952b?auto=format&fit=crop&w=800&q=80',
    description: 'Top-tier box cricket ground with sound system, electronic scoreboard, live streaming cameras, and seating for 40 supporters.',
    amenities: ['Live Scoreboard', 'Sound System', 'Camera Replays', 'Dugouts', 'Secure Valet Parking'],
    slotsCountAvailableToday: 2,
    operatingHours: '05:00 PM - 03:00 AM',
    status: 'approved',
  }
];

export const MOCK_SLOTS: GroundSlot[] = [
  { id: 'slot-1', groundId: 'ground-1', startTime: '16:00', endTime: '17:00', price: 3500, isAvailable: true },
  { id: 'slot-2', groundId: 'ground-1', startTime: '17:00', endTime: '18:00', price: 3500, isAvailable: false },
  { id: 'slot-3', groundId: 'ground-1', startTime: '18:00', endTime: '19:00', price: 3500, isAvailable: true },
  { id: 'slot-4', groundId: 'ground-1', startTime: '19:00', endTime: '20:00', price: 3800, isAvailable: false },
  { id: 'slot-5', groundId: 'ground-1', startTime: '20:00', endTime: '21:00', price: 3800, isAvailable: true },
  { id: 'slot-6', groundId: 'ground-1', startTime: '21:00', endTime: '22:00', price: 3800, isAvailable: true },
  { id: 'slot-7', groundId: 'ground-1', startTime: '22:00', endTime: '23:00', price: 4000, isAvailable: false },
  { id: 'slot-8', groundId: 'ground-1', startTime: '23:00', endTime: '00:00', price: 4000, isAvailable: true },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'book-101',
    referenceCode: 'CRICK-8492',
    userId: 'user-player-1',
    userName: 'Zain Sial',
    userPhone: '0300-1234567',
    groundId: 'ground-1',
    groundName: 'F-6 Box Arena & Indoor Nets',
    groundLocation: 'F-6 Markaz, Islamabad',
    groundImageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=80',
    slotTime: '08:00 PM - 09:00 PM',
    date: '2026-09-05',
    totalPrice: 3800,
    status: 'confirmed',
    paymentMethod: 'cash_on_ground',
    paymentStatus: 'unpaid',
    teamId: 'team-1',
    teamName: 'Islamabad Strikers',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'book-102',
    referenceCode: 'CRICK-7231',
    userId: 'user-player-1',
    userName: 'Zain Sial',
    userPhone: '0300-1234567',
    groundId: 'ground-2',
    groundName: 'Rawal Turf Cricket Hub',
    groundLocation: 'Murree Road, Rawalpindi',
    groundImageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=800&q=80',
    slotTime: '09:00 PM - 10:00 PM',
    date: '2026-09-08',
    totalPrice: 2800,
    status: 'pending',
    paymentMethod: 'easypaisa',
    paymentStatus: 'paid',
    teamId: 'team-1',
    teamName: 'Islamabad Strikers',
    createdAt: '2026-09-02T14:30:00Z',
  },
  {
    id: 'book-103',
    referenceCode: 'CRICK-5510',
    userId: 'user-player-1',
    userName: 'Zain Sial',
    userPhone: '0300-1234567',
    groundId: 'ground-4',
    groundName: 'Saddar Indoor Smash Arena',
    groundLocation: 'Bank Road, Saddar, Rawalpindi',
    groundImageUrl: 'https://images.unsplash.com/photo-1512719355433-e02374b9952b?auto=format&fit=crop&w=800&q=80',
    slotTime: '07:00 PM - 08:00 PM',
    date: '2026-08-28',
    totalPrice: 3200,
    status: 'completed',
    paymentMethod: 'cash_on_ground',
    paymentStatus: 'paid',
    createdAt: '2026-08-25T12:00:00Z',
  },
];

export const MOCK_TEAM: Team = {
  id: 'team-1',
  name: 'Islamabad Strikers',
  captainId: 'user-player-1',
  captainName: 'Zain Sial',
  viceCaptainId: 'mem-2',
  viceCaptainName: 'Mueed Ahmad',
  inviteCode: 'ISB-STRK',
  city: 'Islamabad',
  wins: 14,
  losses: 4,
  draws: 1,
  points: 29,
  members: [
    { id: 'mem-1', name: 'Zain Sial', email: 'zain@crickethub.pk', role: 'captain', playingRole: 'all_rounder', matchesPlayed: 19 },
    { id: 'mem-2', name: 'Mueed Ahmad', email: 'mueed@crickethub.pk', role: 'vice_captain', playingRole: 'bowler', matchesPlayed: 18 },
    { id: 'mem-3', name: 'Shahmeer Khan', email: 'shahmeer@crickethub.pk', role: 'player', playingRole: 'batter', matchesPlayed: 15 },
    { id: 'mem-4', name: 'Bilal Asif', email: 'bilal@gmail.com', role: 'player', playingRole: 'wicketkeeper', matchesPlayed: 12 },
    { id: 'mem-5', name: 'Hamza Tariq', email: 'hamza@gmail.com', role: 'player', playingRole: 'batter', matchesPlayed: 10 },
    { id: 'mem-6', name: 'Usman Ghani', email: 'usman@gmail.com', role: 'player', playingRole: 'bowler', matchesPlayed: 8 },
    {
      id: 'mem-1',
      userId: 'user-player-1',
      name: 'Zain Sial',
      email: 'zain@crickethub.pk',
      role: 'captain',
      playingRole: 'all_rounder',
      permissions: [
        'invite_players',
        'create_matches',
        'manage_squad',
        'manage_stats',
        'approve_players',
        'remove_players',
        'manage_settings',
        'manage_permissions',
        'transfer_captaincy',
        'delete_team',
      ],
      matchesPlayed: 19,
      status: 'active',
    },
    {
      id: 'mem-2',
      userId: 'user-2',
      name: 'Mueed Ahmad',
      email: 'mueed@crickethub.pk',
      role: 'vice_captain',
      playingRole: 'bowler',
      permissions: [
        'invite_players',
        'create_matches',
        'manage_squad',
        'manage_stats',
        'approve_players',
        'remove_players',
        'manage_settings',
      ],
      matchesPlayed: 18,
      status: 'active',
    },
    {
      id: 'mem-3',
      userId: 'user-3',
      name: 'Shahmeer Khan',
      email: 'shahmeer@crickethub.pk',
      role: 'player',
      playingRole: 'batter',
      permissions: [
        'invite_players',
        'create_matches',
        'manage_squad',
        'manage_stats',
      ],
      matchesPlayed: 15,
      status: 'active',
    },
    {
      id: 'mem-4',
      userId: 'user-4',
      name: 'Bilal Asif',
      email: 'bilal@gmail.com',
      role: 'player',
      playingRole: 'wicketkeeper',
      permissions: [],
      matchesPlayed: 12,
      status: 'active',
    },
    {
      id: 'mem-5',
      userId: 'user-5',
      name: 'Hamza Tariq',
      email: 'hamza@gmail.com',
      role: 'player',
      playingRole: 'batter',
      permissions: [],
      matchesPlayed: 10,
      status: 'active',
    },
    {
      id: 'mem-6',
      userId: 'user-6',
      name: 'Usman Ghani',
      email: 'usman@gmail.com',
      role: 'player',
      playingRole: 'bowler',
      permissions: [],
      matchesPlayed: 8,
      status: 'active',
    },
  ],
  createdAt: '2026-06-15T00:00:00Z',
  description: 'A competitive indoor cricket team from the twin cities.',
  isPublic: true,
  recentForm: ['W', 'W', 'L', 'W', 'W'],
  activity: [
    { id: 'activity-1', message: 'Zain booked F-6 Box Arena', createdAt: '2026-09-02T22:00:00Z', type: 'booking' },
    { id: 'activity-2', message: 'Mueed joined the team', createdAt: '2026-08-28T12:00:00Z', type: 'member' },
    { id: 'activity-3', message: 'Islamabad Strikers defeated Capital Kings', createdAt: '2026-08-25T21:00:00Z', type: 'match' },
  ],
  alerts: [
    {
      id: 'alert-1',
      type: 'match_today',
      severity: 'red',
      title: 'MATCH TODAY',
      description: 'Islamabad Strikers vs Rawalpindi Smashers • 9:00 PM at F-6 Box Arena',
      ctaLabel: 'View Match',
      ctaAction: 'view_match',
      timestamp: '2026-09-03T21:00:00Z',
    },
    {
      id: 'alert-2',
      type: 'join_request',
      severity: 'yellow',
      title: 'Join requests pending',
      description: 'Ahsan Rauf requested to join as Batter',
      ctaLabel: 'Review',
      ctaAction: 'review_requests',
      timestamp: '2026-09-03T18:00:00Z',
    },
    {
      id: 'alert-3',
      type: 'unconfirmed_players',
      severity: 'yellow',
      title: "Players haven't confirmed match",
      description: '2 players pending confirmation for tonight’s fixture',
      timestamp: '2026-09-03T17:30:00Z',
    },
    {
      id: 'alert-4',
      type: 'match_completed',
      severity: 'green',
      title: 'Match completed',
      description: 'Defeated Capital Kings by 14 runs (+2 points in standings)',
      timestamp: '2026-08-30T23:00:00Z',
    },
  ],
};

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, teamId: 'team-1', teamName: 'Islamabad Strikers', matchesPlayed: 19, won: 14, lost: 4, points: 29, netRunRate: '+1.84' },
  { rank: 2, teamId: 'team-2', teamName: 'Rawalpindi Smashers', matchesPlayed: 18, won: 13, lost: 5, points: 26, netRunRate: '+1.42' },
  { rank: 3, teamId: 'team-3', teamName: 'Margalla Hawks', matchesPlayed: 17, won: 11, lost: 6, points: 22, netRunRate: '+0.95' },
  { rank: 4, teamId: 'team-4', teamName: 'Cantt Challengers', matchesPlayed: 16, won: 10, lost: 6, points: 20, netRunRate: '+0.32' },
  { rank: 5, teamId: 'team-5', teamName: 'Twin City Kings', matchesPlayed: 16, won: 8, lost: 8, points: 16, netRunRate: '-0.15' },
];

export const MOCK_MATCHES: MatchChallenge[] = [
  {
    id: 'match-1',
    team1Id: 'team-1',
    team1Name: 'Islamabad Strikers',
    groundName: 'F-6 Box Arena',
    matchDate: 'Tonight, 09:00 PM',
    slotTime: '09:00 PM - 10:30 PM',
    overs: 8,
    spotsLeft: 2,
    entryFee: 500,
  },
  {
    id: 'match-2',
    team1Id: 'team-2',
    team1Name: 'Pindi Smashers',
    team2Id: 'team-3',
    team2Name: 'Margalla Hawks',
    groundName: 'Rawal Turf Hub',
    matchDate: 'Tomorrow, 08:00 PM',
    slotTime: '08:00 PM - 09:30 PM',
    overs: 10,
    spotsLeft: 0,
    entryFee: 600,
  },
];

export const MOCK_CRICKET_MATCHES: CricketMatch[] = [
  {
    id: 'cricket-match-1',
    teamId: 'team-1',
    teamName: 'Islamabad Strikers',
    opponentName: 'Capital Kings',
    opponentTeamId: 'team-2',
    groundName: 'F-6 Box Arena',
    groundId: 'ground-1',
    date: '2026-08-30',
    time: '9:00 PM',
    overs: 10,
    format: '10 overs',
    matchType: 'league',
    competitionName: 'Islamabad Box Championship',
    status: 'completed',
    isOfficialLocked: true,
    lockedAt: '2026-08-30T22:45:00Z',
    lockedBy: 'Zain Sial (Captain)',
    teamScore: 142,
    teamWickets: 6,
    teamOvers: 10,
    opponentScore: 128,
    opponentWickets: 9,
    opponentOvers: 10,
    result: 'win',
    margin: '14 runs',
    squad: ['mem-1', 'mem-2', 'mem-3', 'mem-4', 'mem-5', 'mem-6'],
    playingXI: ['mem-1', 'mem-2', 'mem-3', 'mem-4', 'mem-5', 'mem-6'],
    bench: [],
    batting: [
      { playerId: 'mem-1', playerName: 'Zain Sial', runs: 52, balls: 31, fours: 6, sixes: 2, strikeRate: 167.7, dismissal: 'c Mueed b Hamza', isNotOut: false, dotBalls: 8 },
      { playerId: 'mem-2', playerName: 'Mueed Ahmad', runs: 34, balls: 20, fours: 4, sixes: 1, strikeRate: 170.0, dismissal: 'b Bilal', isNotOut: false, dotBalls: 5 },
      { playerId: 'mem-3', playerName: 'Shahmeer Khan', runs: 24, balls: 14, fours: 3, sixes: 1, strikeRate: 171.4, dismissal: 'not out', isNotOut: true, dotBalls: 3 },
      { playerId: 'mem-4', playerName: 'Bilal Asif', runs: 16, balls: 9, fours: 1, sixes: 1, strikeRate: 177.8, dismissal: 'run out (Usman)', isNotOut: false, dotBalls: 2 },
      { playerId: 'mem-5', playerName: 'Hamza Tariq', runs: 8, balls: 5, fours: 1, sixes: 0, strikeRate: 160.0, dismissal: 'c Wicketkeeper b Shahmeer', isNotOut: false, dotBalls: 1 },
      { playerId: 'mem-6', playerName: 'Usman Ghani', runs: 8, balls: 4, fours: 1, sixes: 0, strikeRate: 200.0, dismissal: 'not out', isNotOut: true, dotBalls: 0 },
    ],
    bowling: [
      { playerId: 'mem-1', playerName: 'Zain Sial', overs: 3, maidens: 0, runsConceded: 18, wickets: 3, economy: 6.0, dotBalls: 8, wides: 1, noBalls: 0 },
      { playerId: 'mem-2', playerName: 'Mueed Ahmad', overs: 3, maidens: 0, runsConceded: 21, wickets: 2, economy: 7.0, dotBalls: 6, wides: 2, noBalls: 1 },
      { playerId: 'mem-5', playerName: 'Hamza Tariq', overs: 2, maidens: 0, runsConceded: 27, wickets: 2, economy: 13.5, dotBalls: 3, wides: 1, noBalls: 0 },
      { playerId: 'mem-6', playerName: 'Usman Ghani', overs: 2, maidens: 0, runsConceded: 22, wickets: 1, economy: 11.0, dotBalls: 4, wides: 0, noBalls: 0 },
    ],
    fielding: [
      { playerId: 'mem-1', playerName: 'Zain Sial', catches: 1, runOuts: 0, stumpings: 0, totalDismissals: 1 },
      { playerId: 'mem-2', playerName: 'Mueed Ahmad', catches: 2, runOuts: 0, stumpings: 0, totalDismissals: 2 },
      { playerId: 'mem-3', playerName: 'Shahmeer Khan', catches: 0, runOuts: 1, stumpings: 0, totalDismissals: 1 },
      { playerId: 'mem-6', playerName: 'Usman Ghani', catches: 1, runOuts: 1, stumpings: 0, totalDismissals: 2 },
    ],
    extras: { wides: 6, noBalls: 2, byes: 1, legByes: 1, total: 10 },
    partnerships: [
      { id: 'part-1', player1Name: 'Zain Sial', player2Name: 'Mueed Ahmad', runs: 72, balls: 43, runRate: 10.05 },
      { id: 'part-2', player1Name: 'Shahmeer Khan', player2Name: 'Bilal Asif', runs: 38, balls: 19, runRate: 12.0 },
    ],
    fallOfWickets: [
      { wicketNumber: 1, score: 72, overs: '6.4', playerName: 'Mueed Ahmad' },
      { wicketNumber: 2, score: 98, overs: '8.1', playerName: 'Zain Sial' },
      { wicketNumber: 3, score: 126, overs: '9.2', playerName: 'Bilal Asif' },
    ],
    summaryAwards: {
      playerOfTheMatch: 'Zain Sial (52 runs & 3/18)',
      topScorer: { name: 'Zain Sial', runs: 52, balls: 31 },
      bestBowler: { name: 'Zain Sial', figures: '3/18' },
      bestFielder: { name: 'Mueed Ahmad', dismissals: 2 },
      highestPartnership: { pair: 'Zain Sial & Mueed Ahmad', runs: 72, balls: 43 },
    },
    playerStats: [
      { playerId: 'mem-1', playerName: 'Zain Sial', runs: 52, balls: 31, fours: 6, sixes: 2, overs: 3, bowlingRuns: 18, wickets: 3, catches: 1, runOuts: 0 },
      { playerId: 'mem-2', playerName: 'Mueed Ahmad', runs: 34, balls: 20, fours: 4, sixes: 1, overs: 3, bowlingRuns: 21, wickets: 2, catches: 2, runOuts: 0 },
      { playerId: 'mem-3', playerName: 'Shahmeer Khan', runs: 24, balls: 14, fours: 3, sixes: 1, overs: 0, bowlingRuns: 0, wickets: 0, catches: 0, runOuts: 1 },
      { playerId: 'mem-4', playerName: 'Bilal Asif', runs: 16, balls: 9, fours: 1, sixes: 1, overs: 0, bowlingRuns: 0, wickets: 0, catches: 0, runOuts: 0 },
      { playerId: 'mem-5', playerName: 'Hamza Tariq', runs: 8, balls: 5, fours: 1, sixes: 0, overs: 2, bowlingRuns: 27, wickets: 2, catches: 0, runOuts: 0 },
      { playerId: 'mem-6', playerName: 'Usman Ghani', runs: 8, balls: 4, fours: 1, sixes: 0, overs: 2, bowlingRuns: 22, wickets: 1, catches: 1, runOuts: 1 },
    ],
  },
  {
    id: 'cricket-match-3',
    teamId: 'team-1',
    teamName: 'Islamabad Strikers',
    opponentName: 'Blue Hawks',
    opponentTeamId: 'team-4',
    groundName: 'Rawal Turf Hub',
    groundId: 'ground-2',
    date: '2026-08-22',
    time: '8:00 PM',
    overs: 10,
    format: '10 overs',
    matchType: 'friendly',
    status: 'completed',
    isOfficialLocked: true,
    lockedAt: '2026-08-22T21:40:00Z',
    lockedBy: 'Zain Sial (Captain)',
    teamScore: 118,
    teamWickets: 8,
    teamOvers: 10,
    opponentScore: 121,
    opponentWickets: 6,
    opponentOvers: 9.3,
    result: 'loss',
    margin: '3 wickets',
    squad: ['mem-1', 'mem-2', 'mem-3', 'mem-5'],
    batting: [
      { playerId: 'mem-1', playerName: 'Zain Sial', runs: 32, balls: 24, fours: 3, sixes: 1, strikeRate: 133.3, dismissal: 'c Bowler b Haris', isNotOut: false, dotBalls: 7 },
      { playerId: 'mem-2', playerName: 'Mueed Ahmad', runs: 26, balls: 20, fours: 2, sixes: 1, strikeRate: 130.0, dismissal: 'b Haris', isNotOut: false, dotBalls: 6 },
      { playerId: 'mem-3', playerName: 'Shahmeer Khan', runs: 24, balls: 18, fours: 2, sixes: 0, strikeRate: 133.3, dismissal: 'c Wicketkeeper', isNotOut: false, dotBalls: 5 },
      { playerId: 'mem-5', playerName: 'Hamza Tariq', runs: 18, balls: 14, fours: 1, sixes: 1, strikeRate: 128.6, dismissal: 'not out', isNotOut: true, dotBalls: 4 },
    ],
    bowling: [
      { playerId: 'mem-1', playerName: 'Zain Sial', overs: 2, maidens: 0, runsConceded: 19, wickets: 1, economy: 9.5, dotBalls: 5, wides: 1, noBalls: 0 },
      { playerId: 'mem-2', playerName: 'Mueed Ahmad', overs: 4, maidens: 0, runsConceded: 24, wickets: 2, economy: 6.0, dotBalls: 9, wides: 0, noBalls: 0 },
      { playerId: 'mem-5', playerName: 'Hamza Tariq', overs: 3.3, maidens: 0, runsConceded: 31, wickets: 1, economy: 8.86, dotBalls: 6, wides: 2, noBalls: 1 },
    ],
    fielding: [
      { playerId: 'mem-2', playerName: 'Mueed Ahmad', catches: 1, runOuts: 0, stumpings: 0, totalDismissals: 1 },
      { playerId: 'mem-5', playerName: 'Hamza Tariq', catches: 1, runOuts: 0, stumpings: 0, totalDismissals: 1 },
    ],
    extras: { wides: 5, noBalls: 1, byes: 1, legByes: 1, total: 8 },
    partnerships: [
      { id: 'part-1', player1Name: 'Zain Sial', player2Name: 'Mueed Ahmad', runs: 54, balls: 38, runRate: 8.53 },
    ],
    fallOfWickets: [
      { wicketNumber: 1, score: 54, overs: '6.2', playerName: 'Zain Sial' },
      { wicketNumber: 2, score: 81, overs: '8.4', playerName: 'Mueed Ahmad' },
    ],
    summaryAwards: {
      playerOfTheMatch: 'Haris Khan (Blue Hawks - 4/18)',
      topScorer: { name: 'Zain Sial', runs: 32, balls: 24 },
      bestBowler: { name: 'Mueed Ahmad', figures: '2/24' },
      bestFielder: { name: 'Mueed Ahmad', dismissals: 1 },
    },
    playerStats: [
      { playerId: 'mem-1', playerName: 'Zain Sial', runs: 32, balls: 24, fours: 3, sixes: 1, overs: 2, bowlingRuns: 19, wickets: 1, catches: 0, runOuts: 0 },
      { playerId: 'mem-2', playerName: 'Mueed Ahmad', runs: 26, balls: 20, fours: 2, sixes: 1, overs: 4, bowlingRuns: 24, wickets: 2, catches: 1, runOuts: 0 },
      { playerId: 'mem-3', playerName: 'Shahmeer Khan', runs: 24, balls: 18, fours: 2, sixes: 0, overs: 0, bowlingRuns: 0, wickets: 0, catches: 0, runOuts: 0 },
      { playerId: 'mem-5', playerName: 'Hamza Tariq', runs: 18, balls: 14, fours: 1, sixes: 1, overs: 3.3, bowlingRuns: 31, wickets: 1, catches: 1, runOuts: 0 },
    ],
  },
  {
    id: 'cricket-match-4',
    teamId: 'team-1',
    teamName: 'Islamabad Strikers',
    opponentName: 'Margalla Hawks',
    opponentTeamId: 'team-3',
    groundName: 'F-6 Box Arena',
    groundId: 'ground-1',
    date: '2026-08-15',
    time: '9:00 PM',
    overs: 8,
    format: '8 overs',
    matchType: 'league',
    competitionName: 'Twin Cities League',
    status: 'completed',
    isOfficialLocked: true,
    lockedAt: '2026-08-15T22:15:00Z',
    lockedBy: 'Zain Sial (Captain)',
    teamScore: 96,
    teamWickets: 4,
    teamOvers: 8,
    opponentScore: 96,
    opponentWickets: 7,
    opponentOvers: 8,
    result: 'draw',
    margin: 'level score',
    squad: ['mem-1', 'mem-2', 'mem-4', 'mem-6'],
    batting: [
      { playerId: 'mem-1', playerName: 'Zain Sial', runs: 29, balls: 18, fours: 3, sixes: 1, strikeRate: 161.1, dismissal: 'b Sami', isNotOut: false, dotBalls: 4 },
      { playerId: 'mem-2', playerName: 'Mueed Ahmad', runs: 25, balls: 17, fours: 2, sixes: 0, strikeRate: 147.1, dismissal: 'c Bowler', isNotOut: false, dotBalls: 3 },
      { playerId: 'mem-4', playerName: 'Bilal Asif', runs: 21, balls: 14, fours: 1, sixes: 1, strikeRate: 150.0, dismissal: 'not out', isNotOut: true, dotBalls: 2 },
      { playerId: 'mem-6', playerName: 'Usman Ghani', runs: 12, balls: 9, fours: 1, sixes: 0, strikeRate: 133.3, dismissal: 'not out', isNotOut: true, dotBalls: 1 },
    ],
    bowling: [
      { playerId: 'mem-1', playerName: 'Zain Sial', overs: 2, maidens: 0, runsConceded: 16, wickets: 1, economy: 8.0, dotBalls: 5, wides: 1, noBalls: 0 },
      { playerId: 'mem-2', playerName: 'Mueed Ahmad', overs: 3, maidens: 0, runsConceded: 20, wickets: 1, economy: 6.67, dotBalls: 7, wides: 0, noBalls: 0 },
      { playerId: 'mem-6', playerName: 'Usman Ghani', overs: 3, maidens: 0, runsConceded: 25, wickets: 2, economy: 8.33, dotBalls: 6, wides: 1, noBalls: 0 },
    ],
    fielding: [
      { playerId: 'mem-1', playerName: 'Zain Sial', catches: 1, runOuts: 0, stumpings: 0, totalDismissals: 1 },
      { playerId: 'mem-2', playerName: 'Mueed Ahmad', catches: 0, runOuts: 1, stumpings: 0, totalDismissals: 1 },
      { playerId: 'mem-4', playerName: 'Bilal Asif', catches: 1, runOuts: 0, stumpings: 0, totalDismissals: 1 },
    ],
    extras: { wides: 5, noBalls: 1, byes: 1, legByes: 2, total: 9 },
    partnerships: [
      { id: 'part-1', player1Name: 'Zain Sial', player2Name: 'Mueed Ahmad', runs: 46, balls: 30, runRate: 9.2 },
    ],
    fallOfWickets: [
      { wicketNumber: 1, score: 46, overs: '5.0', playerName: 'Mueed Ahmad' },
      { wicketNumber: 2, score: 62, overs: '6.2', playerName: 'Zain Sial' },
    ],
    playerStats: [
      { playerId: 'mem-1', playerName: 'Zain Sial', runs: 29, balls: 18, fours: 3, sixes: 1, overs: 2, bowlingRuns: 16, wickets: 1, catches: 1, runOuts: 0 },
      { playerId: 'mem-2', playerName: 'Mueed Ahmad', runs: 25, balls: 17, fours: 2, sixes: 0, overs: 3, bowlingRuns: 20, wickets: 1, catches: 0, runOuts: 1 },
      { playerId: 'mem-4', playerName: 'Bilal Asif', runs: 21, balls: 14, fours: 1, sixes: 1, overs: 0, bowlingRuns: 0, wickets: 0, catches: 1, runOuts: 0 },
      { playerId: 'mem-6', playerName: 'Usman Ghani', runs: 12, balls: 9, fours: 1, sixes: 0, overs: 3, bowlingRuns: 25, wickets: 2, catches: 0, runOuts: 0 },
    ],
  },
  {
    id: 'cricket-match-2',
    teamId: 'team-1',
    teamName: 'Islamabad Strikers',
    opponentName: 'Rawalpindi Smashers',
    opponentTeamId: 'team-2',
    groundName: 'F-6 Box Arena',
    groundId: 'ground-1',
    date: '2026-09-12',
    time: '9:00 PM',
    overs: 8,
    format: '8 overs',
    matchType: 'friendly',
    status: 'scheduled',
    squad: ['mem-1', 'mem-2', 'mem-3', 'mem-4'],
    playingXI: ['mem-1', 'mem-2', 'mem-3', 'mem-4'],
    bench: [],
    playerStats: [],
  },
  {
    id: 'cricket-match-5',
    teamId: 'team-1',
    teamName: 'Islamabad Strikers',
    opponentName: 'Chakwal Tigers',
    opponentTeamId: 'team-5',
    groundName: 'Rawal Turf Hub',
    groundId: 'ground-2',
    date: '2026-09-15',
    time: '7:30 PM',
    overs: 10,
    format: '10 overs',
    matchType: 'friendly',
    status: 'pending_approval',
    createdBy: 'Shahmeer Khan',
    notes: 'Requested friendly match against Chakwal Tigers box squad.',
    squad: ['mem-1', 'mem-2', 'mem-3', 'mem-4', 'mem-5'],
    playerStats: [],
  },
  {
    id: 'cricket-match-6',
    teamId: 'team-2',
    teamName: 'Capital Kings',
    opponentName: 'Rawalpindi Warriors',
    opponentTeamId: 'team-3',
    groundName: 'F-6 Box Arena',
    groundId: 'ground-1',
    date: '2026-08-28',
    time: '6:00 PM',
    overs: 8,
    format: '8 overs',
    matchType: 'friendly',
    status: 'completed',
    isOfficialLocked: true,
    teamScore: 105,
    teamWickets: 5,
    opponentScore: 98,
    opponentWickets: 7,
    result: 'win',
    margin: '7 runs',
    squad: ['mem-ck-1', 'mem-ck-2', 'mem-ck-3'],
    playerStats: [
      { playerId: 'mem-ck-1', playerName: 'Kamran Akmal', runs: 45, balls: 26, fours: 5, sixes: 1, overs: 2, bowlingRuns: 14, wickets: 2, catches: 1, runOuts: 0 },
      { playerId: 'mem-ck-2', playerName: 'Asif Ali', runs: 32, balls: 18, fours: 3, sixes: 1, overs: 2, bowlingRuns: 20, wickets: 1, catches: 0, runOuts: 0 },
      { playerId: 'mem-ck-3', playerName: 'Zain Sial', runs: 18, balls: 10, fours: 2, sixes: 0, overs: 2, bowlingRuns: 16, wickets: 1, catches: 0, runOuts: 0 },
    ],
  },
];

export const MOCK_PLATFORM_STATS: PlatformStats = {
  totalUsers: 1420,
  activePlayers: 890,
  totalGrounds: 18,
  activeGrounds: 16,
  totalBookings: 3240,
  bookingsThisWeek: 148,
  totalRevenuePkr: 9840000,
  revenueThisMonthPkr: 1420000,
};

export const MOCK_DISPUTES: DisputeTicket[] = [
  {
    id: 'disp-1',
    ticketNumber: 'DSP-8812',
    bookingId: 'book-101',
    raisedByUserId: 'user-player-1',
    raisedByName: 'Zain Sial',
    raisedByRole: 'player',
    groundName: 'F-6 Box Arena',
    subject: 'Floodlight outage during 2nd innings',
    description: 'The overhead floodlight bank went off for 25 minutes during our booked slot.',
    status: 'open',
    createdAt: '2026-09-02T22:30:00Z',
  },
  {
    id: 'disp-2',
    ticketNumber: 'DSP-8805',
    bookingId: 'book-105',
    raisedByUserId: 'owner-1',
    raisedByName: 'Hamid Ali (Owner)',
    raisedByRole: 'ground_owner',
    groundName: 'Rawal Turf Cricket Hub',
    subject: 'Late cancellation refund dispute',
    description: 'Player cancelled 20 minutes prior to slot start time; requested full refund outside 2-hour window.',
    status: 'in_progress',
    createdAt: '2026-09-01T18:10:00Z',
  },
];

export const MOCK_JOIN_REQUESTS: TeamJoinRequest[] = [
  {
    id: 'join-1',
    teamId: 'team-1',
    teamName: 'Islamabad Strikers',
    userId: 'dir-1',
    playerName: 'Ahsan Rauf',
    playerEmail: 'ahsan@crickethub.pk',
    playingRole: 'batter',
    status: 'pending',
    createdAt: '2026-09-03T14:20:00Z',
  },
  {
    id: 'join-2',
    teamId: 'team-1',
    teamName: 'Islamabad Strikers',
    userId: 'dir-2',
    playerName: 'Haris Mahmood',
    playerEmail: 'haris@crickethub.pk',
    playingRole: 'all_rounder',
    status: 'pending',
    createdAt: '2026-09-02T19:00:00Z',
  },
];

export const MOCK_MY_TEAMS: Team[] = [
  MOCK_TEAM,
  {
    id: 'team-2',
    name: 'Capital Kings',
    captainId: 'user-cap-1',
    captainName: 'Kamran Akmal',
    viceCaptainId: 'user-cap-2',
    viceCaptainName: 'Owais Tariq',
    inviteCode: 'CAP-KING',
    city: 'Islamabad',
    description: 'Premier indoor league contenders competing in Islamabad tournaments.',
    isPublic: true,
    wins: 11,
    losses: 6,
    draws: 0,
    points: 23,
    recentForm: ['W', 'L', 'W', 'W', 'L'],
    createdAt: '2026-05-10T00:00:00Z',
    members: [
      {
        id: 'mem-ck-1',
        userId: 'user-cap-1',
        name: 'Kamran Akmal',
        email: 'kamran@crickethub.pk',
        role: 'captain',
        playingRole: 'batter',
        permissions: [
          'invite_players',
          'create_matches',
          'manage_squad',
          'manage_stats',
          'approve_players',
          'remove_players',
          'manage_settings',
          'manage_permissions',
          'transfer_captaincy',
          'delete_team',
        ],
        matchesPlayed: 17,
        status: 'active',
      },
      {
        id: 'mem-ck-2',
        userId: 'user-cap-2',
        name: 'Owais Tariq',
        email: 'owais.t@crickethub.pk',
        role: 'vice_captain',
        playingRole: 'bowler',
        permissions: [
          'invite_players',
          'create_matches',
          'manage_squad',
          'manage_stats',
          'approve_players',
          'remove_players',
          'manage_settings',
        ],
        matchesPlayed: 16,
        status: 'active',
      },
      {
        id: 'mem-ck-3',
        userId: 'user-player-1',
        name: 'Zain Sial',
        email: 'zain@crickethub.pk',
        role: 'player',
        playingRole: 'batter',
        permissions: ['invite_players'],
        matchesPlayed: 6,
        status: 'active',
      },
      {
        id: 'mem-ck-4',
        userId: 'user-ck-4',
        name: 'Haris Rauf',
        email: 'haris.rauf@gmail.com',
        role: 'player',
        playingRole: 'bowler',
        permissions: [],
        matchesPlayed: 10,
        status: 'active',
      },
      {
        id: 'mem-ck-5',
        userId: 'user-ck-5',
        name: 'Daniyal Ahmed',
        email: 'daniyal@gmail.com',
        role: 'player',
        playingRole: 'all_rounder',
        permissions: [],
        matchesPlayed: 8,
        status: 'active',
      },
    ],
    alerts: [
      {
        id: 'alert-ck-1',
        type: 'match_soon',
        severity: 'yellow',
        title: 'Upcoming League Match',
        description: 'Capital Kings vs Rawalpindi Smashers on Friday at 8:00 PM',
        timestamp: '2026-09-02T12:00:00Z',
      },
    ],
    activity: [
      { id: 'act-ck-1', message: 'Kamran Akmal registered team for Twin Cities Super 8', createdAt: '2026-09-01T10:00:00Z', type: 'match' },
    ],
  },
  {
    id: 'team-3',
    name: 'Rawalpindi Warriors',
    captainId: 'user-rw-1',
    captainName: 'Owais Khan',
    viceCaptainId: 'user-player-1',
    viceCaptainName: 'Zain Sial',
    inviteCode: 'RWP-WARR',
    city: 'Rawalpindi',
    description: 'High tempo tape-ball & box cricket squad based in Pindi Cantt.',
    isPublic: true,
    wins: 10,
    losses: 7,
    draws: 0,
    points: 20,
    recentForm: ['L', 'W', 'W', 'L', 'W'],
    createdAt: '2026-04-18T00:00:00Z',
    members: [
      {
        id: 'mem-rw-1',
        userId: 'user-rw-1',
        name: 'Owais Khan',
        email: 'owais.khan@crickethub.pk',
        role: 'captain',
        playingRole: 'bowler',
        permissions: [
          'invite_players',
          'create_matches',
          'manage_squad',
          'manage_stats',
          'approve_players',
          'remove_players',
          'manage_settings',
          'manage_permissions',
          'transfer_captaincy',
          'delete_team',
        ],
        matchesPlayed: 17,
        status: 'active',
      },
      {
        id: 'mem-rw-2',
        userId: 'user-player-1',
        name: 'Zain Sial',
        email: 'zain@crickethub.pk',
        role: 'vice_captain',
        playingRole: 'all_rounder',
        permissions: [
          'invite_players',
          'create_matches',
          'manage_squad',
          'manage_stats',
          'approve_players',
          'remove_players',
          'manage_settings',
        ],
        matchesPlayed: 11,
        status: 'active',
      },
      {
        id: 'mem-rw-3',
        userId: 'user-rw-3',
        name: 'Sohail Tanvir',
        email: 'sohail@gmail.com',
        role: 'player',
        playingRole: 'bowler',
        permissions: [],
        matchesPlayed: 14,
        status: 'active',
      },
      {
        id: 'mem-rw-4',
        userId: 'user-rw-4',
        name: 'Babar Hayat',
        email: 'babar@gmail.com',
        role: 'player',
        playingRole: 'batter',
        permissions: [],
        matchesPlayed: 9,
        status: 'active',
      },
      {
        id: 'mem-rw-5',
        userId: 'user-rw-5',
        name: 'Asad Ali',
        email: 'asad@gmail.com',
        role: 'player',
        playingRole: 'wicketkeeper',
        permissions: [],
        matchesPlayed: 10,
        status: 'active',
      },
    ],
    alerts: [
      {
        id: 'alert-rw-1',
        type: 'match_completed',
        severity: 'green',
        title: 'Match Won',
        description: 'Rawalpindi Warriors won against Saddar Smashers by 6 wickets',
        timestamp: '2026-08-31T22:00:00Z',
      },
    ],
    activity: [
      { id: 'act-rw-1', message: 'Zain Sial named Vice Captain', createdAt: '2026-08-20T14:00:00Z', type: 'member' },
    ],
  },
];

export const MOCK_MEMBERSHIPS: TeamMembership[] = [
  {
    id: 'membership-1',
    userId: 'user-player-1',
    teamId: 'team-1',
    teamRole: 'captain',
    playingRole: 'all_rounder',
    permissions: [
      'invite_players',
      'create_matches',
      'manage_squad',
      'manage_stats',
      'approve_players',
      'remove_players',
      'manage_settings',
      'manage_permissions',
      'transfer_captaincy',
      'delete_team',
    ],
    status: 'active',
    joinedAt: '2026-06-15T00:00:00Z',
  },
  {
    id: 'membership-2',
    userId: 'user-player-1',
    teamId: 'team-2',
    teamRole: 'player',
    playingRole: 'batter',
    permissions: ['invite_players'],
    status: 'active',
    joinedAt: '2026-07-01T00:00:00Z',
  },
  {
    id: 'membership-3',
    userId: 'user-player-1',
    teamId: 'team-3',
    teamRole: 'vice_captain',
    playingRole: 'all_rounder',
    permissions: [
      'invite_players',
      'create_matches',
      'manage_squad',
      'manage_stats',
      'approve_players',
      'remove_players',
      'manage_settings',
    ],
    status: 'active',
    joinedAt: '2026-07-20T00:00:00Z',
  },
];
