import { Ground, GroundSlot, Booking, Team, LeaderboardEntry, MatchChallenge, PlatformStats, DisputeTicket } from '@/types';

export const MOCK_GROUNDS: Ground[] = [
  {
    id: 'ground-1',
    ownerId: 'owner-1',
    name: 'F-6 Box Arena & Indoor Nets',
    location: 'Super Market, F-6 Markaz',
    address: 'Plot 12, School Road, F-6/1, Islamabad',
    city: 'Islamabad',
    pitchType: 'turf_box',
    hourlyRate: 3500,
    rating: 4.8,
    reviewCount: 124,
    distanceKm: 2.1,
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=80',
    description: 'Premier indoor box cricket with imported AstroTurf, automated bowling machines, LED floodlights, and viewing gallery.',
    amenities: ['Bowling Machine', 'Floodlights', 'Changing Rooms', 'Air Conditioned Dugout', 'Free Parking', 'Cricket Gear Available'],
    slotsCountAvailableToday: 6,
    operatingHours: '04:00 PM - 02:00 AM',
    status: 'approved',
  },
  {
    id: 'ground-2',
    ownerId: 'owner-2',
    name: 'Rawal Turf Cricket Hub',
    location: 'Murree Road, Near Chandni Chowk',
    address: 'Near Commercial Market, Murree Road, Rawalpindi',
    city: 'Rawalpindi',
    pitchType: 'indoor_net',
    hourlyRate: 2800,
    rating: 4.6,
    reviewCount: 98,
    distanceKm: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=800&q=80',
    description: '3 dedicated indoor practice nets with high ceiling, side netting, speed gun radar, and professional coach availability.',
    amenities: ['Speed Gun', 'High Ceiling Nets', 'Dressing Room', 'Refreshments Canteen', 'Video Analysis'],
    slotsCountAvailableToday: 8,
    operatingHours: '02:00 PM - 01:00 AM',
    status: 'approved',
  },
  {
    id: 'ground-3',
    ownerId: 'owner-1',
    name: 'Margalla Sports Complex Nets',
    location: 'Sector G-8/4',
    address: 'Street 33, Sector G-8/4, Islamabad',
    city: 'Islamabad',
    pitchType: 'matting',
    hourlyRate: 2500,
    rating: 4.5,
    reviewCount: 65,
    distanceKm: 3.2,
    imageUrl: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?auto=format&fit=crop&w=800&q=80',
    description: 'All-weather indoor matting wicket arena suitable for serious practice and friendly 6-a-side weekend fixtures.',
    amenities: ['Drinking Water', 'Shower Facilities', 'Seating Stands', 'Tape Ball Provided'],
    slotsCountAvailableToday: 4,
    operatingHours: '09:00 AM - 12:00 AM',
    status: 'approved',
  },
  {
    id: 'ground-4',
    ownerId: 'owner-3',
    name: 'Saddar Indoor Smash Arena',
    location: 'Saddar, Cantt',
    address: 'Bank Road, Saddar, Rawalpindi Cantt',
    city: 'Rawalpindi',
    pitchType: 'turf_box',
    hourlyRate: 3200,
    rating: 4.9,
    reviewCount: 154,
    distanceKm: 6.8,
    imageUrl: 'https://images.unsplash.com/photo-1512719355433-e02374b9952b?auto=format&fit=crop&w=800&q=80',
    description: 'Top-tier box cricket ground with sound system, electronic scoreboard, live streaming cameras, and seating for 40 supporters.',
    amenities: ['Live Scoreboard', 'Sound System', 'Camera Replays', 'Dugouts', 'Secure Valet Parking'],
    slotsCountAvailableToday: 2,
    operatingHours: '05:00 PM - 03:00 AM',
    status: 'approved',
  }
];

export const MOCK_SLOTS: GroundSlot[] = [
  { id: 'slot-1', groundId: 'ground-1', startTime: '16:00', endTime: '17:00', price: 3500, isAvailable: true },
  { id: 'slot-2', groundId: 'ground-1', startTime: '17:00', endTime: '18:00', price: 3500, isAvailable: false },
  { id: 'slot-3', groundId: 'ground-1', startTime: '18:00', endTime: '19:00', price: 3500, isAvailable: true },
  { id: 'slot-4', groundId: 'ground-1', startTime: '19:00', endTime: '20:00', price: 3800, isAvailable: false },
  { id: 'slot-5', groundId: 'ground-1', startTime: '20:00', endTime: '21:00', price: 3800, isAvailable: true },
  { id: 'slot-6', groundId: 'ground-1', startTime: '21:00', endTime: '22:00', price: 3800, isAvailable: true },
  { id: 'slot-7', groundId: 'ground-1', startTime: '22:00', endTime: '23:00', price: 4000, isAvailable: false },
  { id: 'slot-8', groundId: 'ground-1', startTime: '23:00', endTime: '00:00', price: 4000, isAvailable: true },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'book-101',
    referenceCode: 'CRICK-8492',
    userId: 'user-player-1',
    userName: 'Zain Sial',
    userPhone: '0300-1234567',
    groundId: 'ground-1',
    groundName: 'F-6 Box Arena & Indoor Nets',
    groundLocation: 'F-6 Markaz, Islamabad',
    groundImageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=80',
    slotTime: '08:00 PM - 09:00 PM',
    date: '2026-09-05',
    totalPrice: 3800,
    status: 'confirmed',
    paymentMethod: 'cash_on_ground',
    paymentStatus: 'unpaid',
    teamId: 'team-1',
    teamName: 'Islamabad Strikers',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'book-102',
    referenceCode: 'CRICK-7231',
    userId: 'user-player-1',
    userName: 'Zain Sial',
    userPhone: '0300-1234567',
    groundId: 'ground-2',
    groundName: 'Rawal Turf Cricket Hub',
    groundLocation: 'Murree Road, Rawalpindi',
    groundImageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=800&q=80',
    slotTime: '09:00 PM - 10:00 PM',
    date: '2026-09-08',
    totalPrice: 2800,
    status: 'pending',
    paymentMethod: 'easypaisa',
    paymentStatus: 'paid',
    teamId: 'team-1',
    teamName: 'Islamabad Strikers',
    createdAt: '2026-09-02T14:30:00Z',
  },
  {
    id: 'book-103',
    referenceCode: 'CRICK-5510',
    userId: 'user-player-1',
    userName: 'Zain Sial',
    userPhone: '0300-1234567',
    groundId: 'ground-4',
    groundName: 'Saddar Indoor Smash Arena',
    groundLocation: 'Bank Road, Saddar, Rawalpindi',
    groundImageUrl: 'https://images.unsplash.com/photo-1512719355433-e02374b9952b?auto=format&fit=crop&w=800&q=80',
    slotTime: '07:00 PM - 08:00 PM',
    date: '2026-08-28',
    totalPrice: 3200,
    status: 'completed',
    paymentMethod: 'cash_on_ground',
    paymentStatus: 'paid',
    createdAt: '2026-08-25T12:00:00Z',
  },
];

export const MOCK_TEAM: Team = {
  id: 'team-1',
  name: 'Islamabad Strikers',
  captainId: 'user-player-1',
  captainName: 'Zain Sial',
  inviteCode: 'ISB-STRK',
  city: 'Islamabad',
  wins: 14,
  losses: 4,
  draws: 1,
  points: 29,
  members: [
    { id: 'mem-1', name: 'Zain Sial', email: 'zain@crickethub.pk', role: 'captain', matchesPlayed: 19 },
    { id: 'mem-2', name: 'Mueed Ahmad', email: 'mueed@crickethub.pk', role: 'vice_captain', matchesPlayed: 18 },
    { id: 'mem-3', name: 'Shahmeer Khan', email: 'shahmeer@crickethub.pk', role: 'player', matchesPlayed: 15 },
    { id: 'mem-4', name: 'Bilal Asif', email: 'bilal@gmail.com', role: 'player', matchesPlayed: 12 },
    { id: 'mem-5', name: 'Hamza Tariq', email: 'hamza@gmail.com', role: 'player', matchesPlayed: 10 },
    { id: 'mem-6', name: 'Usman Ghani', email: 'usman@gmail.com', role: 'player', matchesPlayed: 8 },
  ],
  createdAt: '2026-06-15T00:00:00Z',
};

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, teamId: 'team-1', teamName: 'Islamabad Strikers', matchesPlayed: 19, won: 14, lost: 4, points: 29, netRunRate: '+1.84' },
  { rank: 2, teamId: 'team-2', teamName: 'Rawalpindi Smashers', matchesPlayed: 18, won: 13, lost: 5, points: 26, netRunRate: '+1.42' },
  { rank: 3, teamId: 'team-3', teamName: 'Margalla Hawks', matchesPlayed: 17, won: 11, lost: 6, points: 22, netRunRate: '+0.95' },
  { rank: 4, teamId: 'team-4', teamName: 'Cantt Challengers', matchesPlayed: 16, won: 10, lost: 6, points: 20, netRunRate: '+0.32' },
  { rank: 5, teamId: 'team-5', teamName: 'Twin City Kings', matchesPlayed: 16, won: 8, lost: 8, points: 16, netRunRate: '-0.15' },
];

export const MOCK_MATCHES: MatchChallenge[] = [
  {
    id: 'match-1',
    team1Id: 'team-1',
    team1Name: 'Islamabad Strikers',
    groundName: 'F-6 Box Arena',
    matchDate: 'Tonight, 09:00 PM',
    slotTime: '09:00 PM - 10:30 PM',
    overs: 8,
    spotsLeft: 2,
    entryFee: 500,
  },
  {
    id: 'match-2',
    team1Id: 'team-2',
    team1Name: 'Pindi Smashers',
    team2Id: 'team-3',
    team2Name: 'Margalla Hawks',
    groundName: 'Rawal Turf Hub',
    matchDate: 'Tomorrow, 08:00 PM',
    slotTime: '08:00 PM - 09:30 PM',
    overs: 10,
    spotsLeft: 0,
    entryFee: 600,
  },
];

export const MOCK_PLATFORM_STATS: PlatformStats = {
  totalUsers: 1420,
  activePlayers: 890,
  totalGrounds: 18,
  activeGrounds: 16,
  totalBookings: 3240,
  bookingsThisWeek: 148,
  totalRevenuePkr: 9840000,
  revenueThisMonthPkr: 1420000,
};

export const MOCK_DISPUTES: DisputeTicket[] = [
  {
    id: 'disp-1',
    ticketNumber: 'DSP-8812',
    bookingId: 'book-101',
    raisedByUserId: 'user-player-1',
    raisedByName: 'Zain Sial',
    raisedByRole: 'player',
    groundName: 'F-6 Box Arena',
    subject: 'Floodlight outage during 2nd innings',
    description: 'The overhead floodlight bank went off for 25 minutes during our booked slot.',
    status: 'open',
    createdAt: '2026-09-02T22:30:00Z',
  },
  {
    id: 'disp-2',
    ticketNumber: 'DSP-8805',
    bookingId: 'book-105',
    raisedByUserId: 'owner-1',
    raisedByName: 'Hamid Ali (Owner)',
    raisedByRole: 'ground_owner',
    groundName: 'Rawal Turf Cricket Hub',
    subject: 'Late cancellation refund dispute',
    description: 'Player cancelled 20 minutes prior to slot start time; requested full refund outside 2-hour window.',
    status: 'in_progress',
    createdAt: '2026-09-01T18:10:00Z',
  },
];
